// account
export const CHECK_IS_ADMIN_START = 'CHECK_IS_ADMIN_START';
export const CHECK_IS_ADMIN_SUCCESS = 'CHECK_IS_ADMIN_SUCCESS';
export const CHECK_IS_ADMIN_ERROR = 'CHECK_IS_ADMIN_ERROR';
export const SET_CURRENT_ACCOUNT = 'SET_CURRENT_ACCOUNT';
export const LOAD_KEYRING = 'LOAD_KEYRING';
export const SET_KEYRING = 'SET_KEYRING';
export const KEYRING_ERROR = 'KEYRING_ERROR';

// api
export const CONNECT_INIT = 'CONNECT_INIT';
export const CONNECT = 'CONNECT';
export const CONNECT_SUCCESS = 'CONNECT_SUCCESS';
export const CONNECT_ERROR = 'CONNECT_ERROR';

// dashboardData
export const GET_USER_BALANCE_START = 'GET_USER_BALANCE_START';
export const GET_USER_BALANCE_ERROR = 'GET_USER_BALANCE_ERROR';
export const GET_USER_BALANCE_SUCCESS = 'GET_USER_BALANCE_SUCCESS';

export const GET_POOL_USER_PARAMS_START = 'GET_POOL_USER_PARAMS_START';
export const GET_POOL_USER_PARAMS_ERROR = 'GET_POOL_USER_PARAMS_ERROR';
export const GET_POOL_USER_PARAMS_SUCCESS = 'GET_POOL_USER_PARAMS_SUCCESS';

export const GET_POOLS_BALANCE_START = 'GET_POOLS_BALANCE_START';
export const GET_POOLS_BALANCE_ERROR = 'GET_POOLS_BALANCE_ERROR';
export const GET_POOLS_BALANCE_SUCCESS = 'GET_POOLS_BALANCE_SUCCESS';

export const GET_POOLS_BORROW_BALANCE_START = 'GET_POOLS_BORROW_BALANCE_START';
export const GET_POOLS_BORROW_BALANCE_ERROR = 'GET_POOLS_BORROW_BALANCE_ERROR';
export const GET_POOLS_BORROW_BALANCE_SUCCESS =
	'GET_POOLS_BORROW_BALANCE_SUCCESS';

export const GET_RATES_DATA_START = 'GET_RATES_DATA_START';
export const GET_RATES_DATA_ERROR = 'GET_RATES_DATA_ERROR';
export const GET_RATES_DATA_SUCCESS = 'GET_RATES_DATA_SUCCESS';

export const RESET_DASHBOARD_DATA = 'RESET_DASHBOARD_DATA';
export const RESET_USER_DATA = 'RESET_USER_DATA';

export const GET_BALANCE_ANNOTATION_START = 'GET_BALANCE_ANNOTATION_START';
export const GET_BALANCE_ANNOTATION_ERROR = 'GET_BALANCE_ANNOTATION_ERROR';
export const GET_BALANCE_ANNOTATION_SUCCESS = 'GET_BALANCE_ANNOTATION_SUCCESS';

export const GET_USER_BALANCE_USD_START = 'GET_USER_BALANCE_USD_START';
export const GET_USER_BALANCE_USD_ERROR = 'GET_USER_BALANCE_USD_ERROR';
export const GET_USER_BALANCE_USD_SUCCESS = 'GET_USER_BALANCE_USD_SUCCESS';

// dashboardUpdates
export const DEPOSIT_UNDERLYING_REQUEST_START =
	'DEPOSIT_UNDERLYING_REQUEST_START';
export const DEPOSIT_UNDERLYING_REQUEST_ERROR =
	'DEPOSIT_UNDERLYING_REQUEST_ERROR';
export const DEPOSIT_UNDERLYING_REQUEST_SUCCESS =
	'DEPOSIT_UNDERLYING_REQUEST_SUCCESS';

export const BORROW_REQUEST_START = 'BORROW_REQUEST_START';
export const BORROW_REQUEST_ERROR = 'BORROW_REQUEST_ERROR';
export const BORROW_REQUEST_SUCCESS = 'BORROW_REQUEST_SUCCESS';

export const REDEEM_REQUEST_START = 'REDEEM_REQUEST_START';
export const REDEEM_REQUEST_ERROR = 'REDEEM_REQUEST_ERROR';
export const REDEEM_REQUEST_SUCCESS = 'REDEEM_REQUEST_SUCCESS';

export const REDEEM_UNDERLYING_REQUEST_START =
	'REDEEM_UNDERLYING_REQUEST_START';
export const REDEEM_UNDERLYING_REQUEST_ERROR =
	'REDEEM_UNDERLYING_REQUEST_ERROR';
export const REDEEM_UNDERLYING_REQUEST_SUCCESS =
	'REDEEM_UNDERLYING_REQUEST_SUCCESS';

export const REDEEM_WRAPPED_REQUEST_START = 'REDEEM_WRAPPED_REQUEST_START';
export const REDEEM_WRAPPED_REQUEST_ERROR = 'REDEEM_WRAPPED_REQUEST_ERROR';
export const REDEEM_WRAPPED_REQUEST_SUCCESS = 'REDEEM_WRAPPED_REQUEST_SUCCESS';

export const REPAY_ALL_REQUEST_START = 'REPAY_ALL_REQUEST_START';
export const REPAY_ALL_REQUEST_ERROR = 'REPAY_ALL_REQUEST_ERROR';
export const REPAY_ALL_REQUEST_SUCCESS = 'REPAY_ALL_REQUEST_SUCCESS';

export const REPAY_REQUEST_START = 'REPAY_REQUEST_START';
export const REPAY_REQUEST_ERROR = 'REPAY_REQUEST_ERROR';
export const REPAY_REQUEST_SUCCESS = 'REPAY_REQUEST_SUCCESS';

export const REPAY_ON_BEHALF_REQUEST_START = 'REPAY_ON_BEHALF_REQUEST_START';
export const REPAY_ON_BEHALF_REQUEST_ERROR = 'REPAY_ON_BEHALF_REQUEST_ERROR';
export const REPAY_ON_BEHALF_REQUEST_SUCCESS =
	'REPAY_ON_BEHALF_REQUEST_SUCCESS';

export const TRANSFER_WRAPPED_START = 'TRANSFER_WRAPPED_START';
export const TRANSFER_WRAPPED_ERROR = 'TRANSFER_WRAPPED_ERROR';
export const TRANSFER_WRAPPED_SUCCESS = 'TRANSFER_WRAPPED_SUCCESS';

export const DISABLE_IS_COLLATERAL_START = 'DISABLE_IS_COLLATERAL_START';
export const DISABLE_IS_COLLATERAL_ERROR = 'DISABLE_IS_COLLATERAL_ERROR';
export const DISABLE_IS_COLLATERAL_SUCCESS = 'DISABLE_IS_COLLATERAL_SUCCESS';

export const ENABLE_IS_COLLATERAL_START = 'ENABLE_IS_COLLATERAL_START';
export const ENABLE_IS_COLLATERAL_ERROR = 'ENABLE_IS_COLLATERAL_ERROR';
export const ENABLE_IS_COLLATERAL_SUCCESS = 'ENABLE_IS_COLLATERAL_SUCCESS';

export const RESET_USER_REQUESTS = 'RESET_USER_REQUESTS';

// liquidationAdminData
export const GET_LIQUIDATION_POOLS_BALANCE_START =
	'GET_LIQUIDATION_POOLS_BALANCE_START';
export const GET_LIQUIDATION_POOLS_BALANCE_ERROR =
	'GET_LIQUIDATION_POOLS_BALANCE_ERROR';
export const GET_LIQUIDATION_POOLS_BALANCE_SUCCESS =
	'GET_LIQUIDATION_POOLS_BALANCE_SUCCESS';

export const GET_LIQUIDATION_POOL_PARAMS_START =
	'GET_LIQUIDATION_POOL_PARAMS_START';
export const GET_LIQUIDATION_POOL_PARAMS_ERROR =
	'GET_LIQUIDATION_POOL_PARAMS_ERROR';
export const GET_LIQUIDATION_POOL_PARAMS_SUCCESS =
	'GET_LIQUIDATION_POOL_PARAMS_SUCCESS';

export const GET_RISK_MANAGER_PARAMS_START = 'GET_RISK_MANAGER_PARAMS_START';
export const GET_RISK_MANAGER_PARAMS_SUCCESS =
	'GET_RISK_MANAGER_PARAMS_SUCCESS';
export const GET_RISK_MANAGER_PARAMS_ERROR = 'GET_RISK_MANAGER_PARAMS_ERROR';

export const GET_LIQUIDATION_BALANCING_PERIOD_START =
	'GET_LIQUIDATION_BALANCING_PERIOD_START';
export const GET_LIQUIDATION_BALANCING_PERIOD_ERROR =
	'GET_LIQUIDATION_BALANCING_PERIOD_ERROR';
export const GET_LIQUIDATION_BALANCING_PERIOD_SUCCESS =
	'GET_LIQUIDATION_BALANCING_PERIOD_SUCCESS';

// liquidationAdminUpdates
export const RESET_LIQUIDATION_ADMIN_UPDATE_REQUESTS =
	'RESET_LIQUIDATION_ADMIN_UPDATE_REQUESTS';

export const SET_BALANCE_RATIO_START = 'SET_BALANCE_RATIO_START';
export const SET_BALANCE_RATIO_ERROR = 'SET_BALANCE_RATIO_ERROR';
export const SET_BALANCE_RATIO_SUCCESS = 'SET_BALANCE_RATIO_SUCCESS';

export const SET_DEVIATION_THRESHOLD_START = 'SET_DEVIATION_THRESHOLD_START';
export const SET_DEVIATION_THRESHOLD_ERROR = 'SET_DEVIATION_THRESHOLD_ERROR';
export const SET_DEVIATION_THRESHOLD_SUCCESS =
	'SET_DEVIATION_THRESHOLD_SUCCESS';

export const SET_LIQUIDATION_FEE_START = 'SET_LIQUIDATION_FEE_START';
export const SET_LIQUIDATION_FEE_ERROR = 'SET_LIQUIDATION_FEE_ERROR';
export const SET_LIQUIDATION_FEE_SUCCESS = 'SET_LIQUIDATION_FEE_SUCCESS';

export const SET_THRESHOLD_REQUEST_START = 'SET_THRESHOLD_REQUEST_START';
export const SET_THRESHOLD_REQUEST_SUCCESS = 'SET_THRESHOLD_REQUEST_SUCCESS';
export const SET_THRESHOLD_REQUEST_ERROR = 'SET_THRESHOLD_REQUEST_ERROR';

export const SET_LIQUIDATIONS_MAX_ATTEMPTS_START =
	'SET_LIQUIDATIONS_MAX_ATTEMPTS_START';
export const SET_LIQUIDATIONS_MAX_ATTEMPTS_SUCCESS =
	'SET_LIQUIDATIONS_MAX_ATTEMPTS_SUCCESS';
export const SET_LIQUIDATIONS_MAX_ATTEMPTS_ERROR =
	'SET_LIQUIDATIONS_MAX_ATTEMPTS_ERROR';

export const SET_MIN_PARTIAL_LIQUIDATION_SUM_START =
	'SET_MIN_PARTIAL_LIQUIDATION_SUM_START';
export const SET_MIN_PARTIAL_LIQUIDATION_SUM_SUCCESS =
	'SET_MIN_PARTIAL_LIQUIDATION_SUM_SUCCESS';
export const SET_MIN_PARTIAL_LIQUIDATION_SUM_ERROR =
	'SET_MIN_PARTIAL_LIQUIDATION_SUM_ERROR';

export const SET_BALANCING_PERIOD_START = 'SET_BALANCING_PERIOD_START';
export const SET_BALANCING_PERIOD_ERROR = 'SET_BALANCING_PERIOD_ERROR';
export const SET_BALANCING_PERIOD_SUCCESS = 'SET_BALANCING_PERIOD_SUCCESS';

export const SET_MAX_IDEAL_BALANCE_START = 'SET_MAX_IDEAL_BALANCE_START';
export const SET_MAX_IDEAL_BALANCE_ERROR = 'SET_MAX_IDEAL_BALANCE_ERROR';
export const SET_MAX_IDEAL_BALANCE_SUCCESS = 'SET_MAX_IDEAL_BALANCE_SUCCESS';

//protocolAdminData
export const GET_WHITELIST_MODE_START = 'GET_WHITELIST_MODE_START';
export const GET_WHITELIST_MODE_ERROR = 'GET_WHITELIST_MODE_ERROR';
export const GET_WHITELIST_MODE_SUCCESS = 'GET_WHITELIST_MODE_SUCCESS';

export const GET_CONTROLLER_PARAMS_START = 'GET_CONTROLLER_PARAMS_START';
export const GET_CONTROLLER_PARAMS_SUCCESS = 'GET_CONTROLLER_PARAMS_SUCCESS';
export const GET_CONTROLLER_PARAMS_ERROR = 'GET_CONTROLLER_PARAMS_ERROR';

export const GET_MINTEREST_MODEL_PARAMS_START =
	'GET_MINTEREST_MODEL_PARAMS_START';
export const GET_MINTEREST_MODEL_PARAMS_SUCCESS =
	'GET_MINTEREST_MODEL_PARAMS_SUCCESS';
export const GET_MINTEREST_MODEL_PARAMS_ERROR =
	'GET_MINTEREST_MODEL_PARAMS_ERROR';

export const GET_PAUSE_KEEPERS_START = 'GET_PAUSE_KEEPERS_START';
export const GET_PAUSE_KEEPERS_SUCCESS = 'GET_PAUSE_KEEPERS_SUCCESS';
export const GET_PAUSE_KEEPERS_ERROR = 'GET_PAUSE_KEEPERS_ERROR';

export const GET_LOCKED_PRICES_START = 'GET_LOCKED_PRICES_START';
export const GET_LOCKED_PRICES_ERROR = 'GET_LOCKED_PRICES_ERROR';
export const GET_LOCKED_PRICES_SUCCESS = 'GET_LOCKED_PRICES_SUCCESS';

export const GET_MNT_SPEED_START = 'GET_MNT_SPEED_START';
export const GET_MNT_SPEED_ERROR = 'GET_MNT_SPEED_ERROR';
export const GET_MNT_SPEED_SUCCESS = 'GET_MNT_SPEED_SUCCESS';

export const GET_MNT_RATE_START = 'GET_MNT_RATE_START';
export const GET_MNT_RATE_ERROR = 'GET_MNT_RATE_ERROR';
export const GET_MNT_RATE_SUCCESS = 'GET_MNT_RATE_SUCCESS';

//protocolAdminUpdates
export const RESET_PROTOCOL_ADMIN_REQUESTS = 'RESET_PROTOCOL_ADMIN_REQUESTS';

export const SWITCH_WHITELIST_MODE_START = 'SWITCH_WHITELIST_MODE_START';
export const SWITCH_WHITELIST_MODE_ERROR = 'SWITCH_WHITELIST_MODE_ERROR';
export const SWITCH_WHITELIST_MODE_SUCCESS = 'SWITCH_WHITELIST_MODE_SUCCESS';

export const SET_PROTOCOL_INTEREST_FACTOR_START =
	'SET_PROTOCOL_INTEREST_FACTOR_START';
export const SET_PROTOCOL_INTEREST_FACTOR_SUCCESS =
	'SET_PROTOCOL_INTEREST_FACTOR_SUCCESS';
export const SET_PROTOCOL_INTEREST_FACTOR_ERROR =
	'SET_PROTOCOL_INTEREST_FACTOR_ERROR';

export const SET_PROTOCOL_INTEREST_THRESHOLD_START =
	'SET_PROTOCOL_INTEREST_THRESHOLD_START';
export const SET_PROTOCOL_INTEREST_THRESHOLD_SUCCESS =
	'SET_PROTOCOL_INTEREST_THRESHOLD_SUCCESS';
export const SET_PROTOCOL_INTEREST_THRESHOLD_ERROR =
	'SET_PROTOCOL_INTEREST_THRESHOLD_ERROR';

export const SET_COLLATERAL_FACTOR_REQUEST_START =
	'SET_COLLATERAL_FACTOR_REQUEST_START';
export const SET_COLLATERAL_FACTOR_REQUEST_SUCCESS =
	'SET_COLLATERAL_FACTOR_REQUEST_SUCCESS';
export const SET_COLLATERAL_FACTOR_REQUEST_ERROR =
	'SET_COLLATERAL_FACTOR_REQUEST_ERROR';

export const SET_BASE_RATE_PER_YEAR_REQUEST_START =
	'SET_BASE_RATE_PER_YEAR_REQUEST_START';
export const SET_BASE_RATE_PER_YEAR_REQUEST_SUCCESS =
	'SET_BASE_RATE_PER_YEAR_REQUEST_SUCCESS';
export const SET_BASE_RATE_PER_YEAR_REQUEST_ERROR =
	'SET_BASE_RATE_PER_YEAR_REQUEST_ERROR';

export const SET_MULTIPLIER_PER_YEAR_REQUEST_START =
	'SET_MULTIPLIER_PER_YEAR_REQUEST_START';
export const SET_MULTIPLIER_PER_YEAR_REQUEST_SUCCESS =
	'SET_MULTIPLIER_PER_YEAR_REQUEST_SUCCESS';
export const SET_MULTIPLIER_PER_YEAR_REQUEST_ERROR =
	'SET_MULTIPLIER_PER_YEAR_REQUEST_ERROR';

export const SET_KINK_REQUEST_START = 'SET_KINK_REQUEST_START';
export const SET_KINK_REQUEST_SUCCESS = 'SET_KINK_REQUEST_SUCCESS';
export const SET_KINK_REQUEST_ERROR = 'SET_KINK_REQUEST_ERROR';

export const SET_JUMP_MULTIPLIER_PER_YEAR_REQUEST_START =
	'SET_JUMP_MULTIPLIER_PER_YEAR_REQUEST_START';
export const SET_JUMP_MULTIPLIER_PER_YEAR_REQUEST_SUCCESS =
	'SET_JUMP_MULTIPLIER_PER_YEAR_REQUEST_SUCCESS';
export const SET_JUMP_MULTIPLIER_PER_YEAR_REQUEST_ERROR =
	'SET_JUMP_MULTIPLIER_PER_YEAR_REQUEST_ERROR';

export const SET_BORROW_CAP_START = 'SET_BORROW_CAP_START';
export const SET_BORROW_CAP_ERROR = 'SET_BORROW_CAP_ERROR';
export const SET_BORROW_CAP_SUCCESS = 'SET_BORROW_CAP_SUCCESS';

export const PAUSE_OPERATION_START = 'PAUSE_OPERATION_START';
export const PAUSE_OPERATION_SUCCESS = 'PAUSE_OPERATION_SUCCESS';
export const PAUSE_OPERATION_ERROR = 'PAUSE_OPERATION_ERROR';

export const RESUME_OPERATION_START = 'RESUME_OPERATION_START';
export const RESUME_OPERATION_SUCCESS = 'RESUME_OPERATION_SUCCESS';
export const RESUME_OPERATION_ERROR = 'RESUME_OPERATION_ERROR';

export const LOCK_PRICE_REQUEST_START = 'LOCK_PRICE_REQUEST_START';
export const LOCK_PRICE_REQUEST_ERROR = 'LOCK_PRICE_REQUEST_ERROR';
export const LOCK_PRICE_REQUEST_SUCCESS = 'LOCK_PRICE_REQUEST_SUCCESS';

export const UNLOCK_PRICE_REQUEST_START = 'UNLOCK_PRICE_REQUEST_START';
export const UNLOCK_PRICE_REQUEST_ERROR = 'UNLOCK_PRICE_REQUEST_ERROR';
export const UNLOCK_PRICE_REQUEST_SUCCESS = 'UNLOCK_PRICE_REQUEST_SUCCESS';

export const FEED_VALUES_REQUEST_START = 'FEED_VALUES_REQUEST_START';
export const FEED_VALUES_REQUEST_ERROR = 'FEED_VALUES_REQUEST_ERROR';
export const FEED_VALUES_REQUEST_SUCCESS = 'FEED_VALUES_REQUEST_SUCCESS';

export const ENABLE_MNT_MINTING_START = 'ENABLE_MNT_MINTING_START';
export const ENABLE_MNT_MINTING_ERROR = 'ENABLE_MNT_MINTING_ERROR';
export const ENABLE_MNT_MINTING_SUCCESS = 'ENABLE_MNT_MINTING_SUCCESS';

export const DISABLE_MNT_MINTING_START = 'DISABLE_MNT_MINTING_START';
export const DISABLE_MNT_MINTING_ERROR = 'DISABLE_MNT_MINTING_ERROR';
export const DISABLE_MNT_MINTING_SUCCESS = 'DISABLE_MNT_MINTING_SUCCESS';

export const SET_MNT_RATE_FOR_SIDE_START = 'SET_MNT_RATE_FOR_SIDE_START';
export const SET_MNT_RATE_FOR_SIDE_ERROR = 'SET_MNT_RATE_FOR_SIDE_ERROR';
export const SET_MNT_RATE_FOR_SIDE_SUCCESS = 'SET_MNT_RATE_FOR_SIDE_SUCCESS';

export const SET_LIQUIDATION_POOL_TOTAL_START =
	'SET_LIQUIDATION_POOL_TOTAL_START';
export const SET_LIQUIDATION_POOL_TOTAL_ERROR =
	'SET_LIQUIDATION_POOL_TOTAL_ERROR';
export const SET_LIQUIDATION_POOL_TOTAL_SUCCESS =
	'SET_LIQUIDATION_POOL_TOTAL_SUCCESS';

export const GET_PROTOCOL_ENABLED_CURRENCIES_START =
	'GET_PROTOCOL_ENABLED_CURRENCIES_START';
export const GET_PROTOCOL_ENABLED_CURRENCIES_ERROR =
	'GET_PROTOCOL_ENABLED_CURRENCIES_ERROR';
export const GET_PROTOCOL_ENABLED_CURRENCIES_SUCCESS =
	'GET_PROTOCOL_ENABLED_CURRENCIES_SUCCESS';

export const GET_PROTOCOL_ENABLED_WRAPPED_CURRENCIES_START =
	'GET_PROTOCOL_ENABLED_WRAPPED_CURRENCIES_START';
export const GET_PROTOCOL_ENABLED_WRAPPED_CURRENCIES_ERROR =
	'GET_PROTOCOL_ENABLED_WRAPPED_CURRENCIES_ERROR';
export const GET_PROTOCOL_ENABLED_WRAPPED_CURRENCIES_SUCCESS =
	'GET_PROTOCOL_ENABLED_WRAPPED_CURRENCIES_SUCCESS';

export const GET_HYPOTHETICAL_LIQUIDITY_DATA_START =
	'GET_HYPOTHETICAL_LIQUIDITY_DATA_START';
export const GET_HYPOTHETICAL_LIQUIDITY_DATA_ERROR =
	'GET_HYPOTHETICAL_LIQUIDITY_DATA_ERROR';
export const GET_HYPOTHETICAL_LIQUIDITY_DATA_SUCCESS =
	'GET_HYPOTHETICAL_LIQUIDITY_DATA_SUCCESS';

export const GET_OPERATION_INFO_START = 'GET_OPERATION_INFO_START';
export const GET_OPERATION_INFO_ERROR = 'GET_OPERATION_INFO_ERROR';
export const GET_OPERATION_INFO_SUCCESS = 'GET_OPERATION_INFO_SUCCESS';

export const RESET_OPERATION_INFO = 'RESET_OPERATION_INFO';

// Governance
export const GET_PROPOSALS_START = 'GET_PROPOSALS_START';
export const GET_PROPOSALS_ERROR = 'GET_PROPOSALS_ERROR';
export const GET_PROPOSALS_SUCCSESS = 'GET_PROPOSALS_SUCCSESS';

export const GET_METADATA_START = 'GET_METADATA_START';
export const GET_METADATA_ERROR = 'GET_METADATA_ERROR';
export const GET_METADATA_SUCCESS = 'GET_METADATA_SUCCESS';

export const PROPOSE_EXTRINSIC_START = 'PROPOSE_EXTRINSIC_START';
export const PROPOSE_EXTRINSIC_SUCCESS = 'PROPOSE_EXTRINSIC_SUCCESS';
export const PROPOSE_EXTRINSIC_ERROR = 'PROPOSE_EXTRINSIC_ERROR';

export const TRANSFER_TO_LIQUIDATION_POOL_START =
	'TRANSFER_TO_LIQUIDATION_POOL_START';
export const TRANSFER_TO_LIQUIDATION_POOL_SUCCESS =
	'TRANSFER_TO_LIQUIDATION_POOL_SUCCESS';
export const TRANSFER_TO_LIQUIDATION_POOL_ERROR =
	'TRANSFER_TO_LIQUIDATION_POOL_ERROR';
