// TODO
export const CONNECT_INIT = 'CONNECT_INIT';
export const CONNECT = 'CONNECT';
export const CONNECT_SUCCESS = 'CONNECT_SUCCESS';
export const CONNECT_ERROR = 'CONNECT_ERROR';
export const LOAD_KEYRING = 'LOAD_KEYRING';
export const SET_KEYRING = 'SET_KEYRING';
export const KEYRING_ERROR = 'KEYRING_ERROR';
// economicUpdatesReducer
export const SET_BASE_RATE_PER_BLOCK_REQUEST_START =
	'SET_BASE_RATE_PER_BLOCK_REQUEST_START';
export const SET_BASE_RATE_PER_BLOCK_REQUEST_SUCCESS =
	'SET_BASE_RATE_PER_BLOCK_REQUEST_SUCCESS';
export const SET_BASE_RATE_PER_BLOCK_REQUEST_ERROR =
	'SET_BASE_RATE_PER_BLOCK_REQUEST_ERROR';

export const SET_JUMP_MULTIPLIER_PER_BLOCK_REQUEST_START =
	'SET_JUMP_MULTIPLIER_PER_BLOCK_REQUEST_START';
export const SET_JUMP_MULTIPLIER_PER_BLOCK_REQUEST_SUCCESS =
	'SET_JUMP_MULTIPLIER_PER_BLOCK_REQUEST_SUCCESS';
export const SET_JUMP_MULTIPLIER_PER_BLOCK_REQUEST_ERROR =
	'SET_JUMP_MULTIPLIER_PER_BLOCK_REQUEST_ERROR';

export const SET_KINK_REQUEST_START = 'SET_KINK_REQUEST_START';
export const SET_KINK_REQUEST_SUCCESS = 'SET_KINK_REQUEST_SUCCESS';
export const SET_KINK_REQUEST_ERROR = 'SET_KINK_REQUEST_ERROR';

export const SET_MULTIPLIER_PER_BLOCK_REQUEST_START =
	'SET_MULTIPLIER_PER_BLOCK_REQUEST_START';
export const SET_MULTIPLIER_PER_BLOCK_REQUEST_SUCCESS =
	'SET_MULTIPLIER_PER_BLOCK_REQUEST_SUCCESS';
export const SET_MULTIPLIER_PER_BLOCK_REQUEST_ERROR =
	'SET_MULTIPLIER_PER_BLOCK_REQUEST_ERROR';
// adminReducer
export const DEPOSIT_UNDERLYING_REQUEST_START =
	'DEPOSIT_UNDERLYING_REQUEST_START';
export const DEPOSIT_UNDERLYING_REQUEST_ERROR =
	'DEPOSIT_UNDERLYING_REQUEST_ERROR';
export const DEPOSIT_UNDERLYING_REQUEST_SUCCESS =
	'DEPOSIT_UNDERLYING_REQUEST_SUCCESS';

export const REDEEM_REQUEST_START = 'REDEEM_REQUEST_START';
export const REDEEM_REQUEST_ERROR = 'REDEEM_REQUEST_ERROR';
export const REDEEM_REQUEST_SUCCESS = 'REDEEM_REQUEST_SUCCESS';

export const REDEEM_UNDERLYING_REQUEST_START =
	'REDEEM_UNDERLYING_REQUEST_START';
export const REDEEM_UNDERLYING_REQUEST_ERROR =
	'REDEEM_UNDERLYING_REQUEST_ERROR';
export const REDEEM_UNDERLYING_REQUEST_SUCCESS =
	'REDEEM_UNDERLYING_REQUEST_SUCCESS';

export const REDEEM_WRAPPED_REQUEST_START = 'REDEEM_WRAPPED_REQUEST_START';
export const REDEEM_WRAPPED_REQUEST_ERROR = 'REDEEM_WRAPPED_REQUEST_ERROR';
export const REDEEM_WRAPPED_REQUEST_SUCCESS = 'REDEEM_WRAPPED_REQUEST_SUCCESS';

export const BORROW_REQUEST_START = 'BORROW_REQUEST_START';
export const BORROW_REQUEST_ERROR = 'BORROW_REQUEST_ERROR';
export const BORROW_REQUEST_SUCCESS = 'BORROW_REQUEST_SUCCESS';

export const REPAY_ALL_REQUEST_START = 'REPAY_ALL_REQUEST_START';
export const REPAY_ALL_REQUEST_ERROR = 'REPAY_ALL_REQUEST_ERROR';
export const REPAY_ALL_REQUEST_SUCCESS = 'REPAY_ALL_REQUEST_SUCCESS';

export const REPAY_REQUEST_START = 'REPAY_REQUEST_START';
export const REPAY_REQUEST_ERROR = 'REPAY_REQUEST_ERROR';
export const REPAY_REQUEST_SUCCESS = 'REPAY_REQUEST_SUCCESS';

export const REPAY_ON_BEHALF_REQUEST_START = 'REPAY_ON_BEHALF_REQUEST_START';
export const REPAY_ON_BEHALF_REQUEST_ERROR = 'REPAY_ON_BEHALF_REQUEST_ERROR';
export const REPAY_ON_BEHALF_REQUEST_SUCCESS =
	'REPAY_ON_BEHALF_REQUEST_SUCCESS';

export const DEPOSIT_INSURANCE_REQUEST_START =
	'DEPOSIT_INSURANCE_REQUEST_START';
export const DEPOSIT_INSURANCE_REQUEST_ERROR =
	'DEPOSIT_INSURANCE_REQUEST_ERROR';
export const DEPOSIT_INSURANCE_REQUEST_SUCCESS =
	'DEPOSIT_INSURANCE_REQUEST_SUCCESS';

export const REDEEM_INSURANCE_REQUEST_START = 'REDEEM_INSURANCE_REQUEST_START';
export const REDEEM_INSURANCE_REQUEST_ERROR = 'REDEEM_INSURANCE_REQUEST_ERROR';
export const REDEEM_INSURANCE_REQUEST_SUCCESS =
	'REDEEM_INSURANCE_REQUEST_SUCCESS';
