// TODO
export const CONNECT_INIT = 'CONNECT_INIT';
export const CONNECT = 'CONNECT';
export const CONNECT_SUCCESS = 'CONNECT_SUCCESS';
export const CONNECT_ERROR = 'CONNECT_ERROR';
export const LOAD_KEYRING = 'LOAD_KEYRING';
export const SET_KEYRING = 'SET_KEYRING';
export const KEYRING_ERROR = 'KEYRING_ERROR';
// economicUpdates
export const SET_BASE_RATE_PER_BLOCK_REQUEST_START =
	'SET_BASE_RATE_PER_BLOCK_REQUEST_START';
export const SET_BASE_RATE_PER_BLOCK_REQUEST_SUCCESS =
	'SET_BASE_RATE_PER_BLOCK_REQUEST_SUCCESS';
export const SET_BASE_RATE_PER_BLOCK_REQUEST_ERROR =
	'SET_BASE_RATE_PER_BLOCK_REQUEST_ERROR';

export const SET_JUMP_MULTIPLIER_PER_BLOCK_REQUEST_START =
	'SET_JUMP_MULTIPLIER_PER_BLOCK_REQUEST_START';
export const SET_JUMP_MULTIPLIER_PER_BLOCK_REQUEST_SUCCESS =
	'SET_JUMP_MULTIPLIER_PER_BLOCK_REQUEST_SUCCESS';
export const SET_JUMP_MULTIPLIER_PER_BLOCK_REQUEST_ERROR =
	'SET_JUMP_MULTIPLIER_PER_BLOCK_REQUEST_ERROR';

export const SET_KINK_REQUEST_START = 'SET_KINK_REQUEST_START';
export const SET_KINK_REQUEST_SUCCESS = 'SET_KINK_REQUEST_SUCCESS';
export const SET_KINK_REQUEST_ERROR = 'SET_KINK_REQUEST_ERROR';

export const SET_MULTIPLIER_PER_BLOCK_REQUEST_START =
	'SET_MULTIPLIER_PER_BLOCK_REQUEST_START';
export const SET_MULTIPLIER_PER_BLOCK_REQUEST_SUCCESS =
	'SET_MULTIPLIER_PER_BLOCK_REQUEST_SUCCESS';
export const SET_MULTIPLIER_PER_BLOCK_REQUEST_ERROR =
	'SET_MULTIPLIER_PER_BLOCK_REQUEST_ERROR';
